default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: senha
  host: localhost

development:
  <<: *default
  database: projeto_edomi_development

test:
  <<: *default
  database: projeto_edomi_test
